DROP TABLE IF EXISTS CAR;  
CREATE TABLE CAR (  
C_Id INT AUTO_INCREMENT  PRIMARY KEY,  
Model_Name VARCHAR(20) NOT NULL,  
Brand VARCHAR(20) NOT NULL, 
Color VARCHAR(10) NOT NULL,
No_of_Pas VARCHAR(10) NOT NULL,
PRICE NUMBER NOT NULL,
Image VARCHAR(50) ,
Fueltype VARCHAR(10) NOT NULL
);   